@base_url=http://localhost:8081

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI3MjQ3ODV9.PdCVJLkV7OK3HABAXxtADcb5DmmE8DERJLQUqUo82t4

{
    "text": "test 1"
}