@base_url=http://localhost:8081

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI1NjA5MDB9.Df07L2hIkPK4OV9qjlv0f_IxuI9_o6e_i9knWpAoWGQ

{
    "text": "test 1"
}